#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""PDF generator functions for batch 6 clinical tests (part 1: tests 1-5)."""

from kalyo_pdf_common import LIKERT_4_SHORT, build_instrument_pdf

LIKERT_0_4 = ["0", "1", "2", "3", "4"]
LIKERT_1_4 = ["1", "2", "3", "4"]
LIKERT_1_5 = ["1", "2", "3", "4", "5"]
YES_NO = ["No", "Sí"]
LIKERT_0_3 = ["0", "1", "2", "3"]


def gen_sf36():
    items = [
        "Realizar actividades extenuantes (correr, levantar objetos pesados)",
        "Realizar actividades moderadas (mover una mesa, pasar la aspiradora)",
        "Levantar o cargar la bolsa de la compra",
        "Subir varios tramos de escaleras",
        "Subir un tramo de escaleras",
        "Agacharse, arrodillarse o inclinarse",
        "Caminar más de 1 km",
        "Caminar varios centenares de metros",
        "Caminar 100 metros",
        "Bañarse o vestirse solo(a)",
        "Reducir tiempo en el trabajo por problemas físicos",
        "Lograr menos de lo deseado por problemas físicos",
        "Limitado(a) en tipo de trabajo por problemas físicos",
        "Dificultad para realizar trabajo por problemas físicos",
        "¿Cuánto dolor corporal ha tenido en las últimas 4 semanas?",
        "¿Hasta qué punto el dolor le ha interferido en el trabajo habitual?",
        "¿Diría que su salud en general es…?",
        "Parece enfermar más fácilmente que otras personas",
        "Estoy tan sano(a) como cualquier persona",
        "Espero que empeore mi salud",
        "Mi salud es excelente",
        "¿Se siente lleno(a) de vitalidad?",
        "¿Ha estado muy nervioso(a)?",
        "¿Se ha sentido tan deprimido(a) que nada le animaba?",
        "¿Se ha sentido calmado(a) y tranquilo(a)?",
        "¿Ha tenido mucha energía?",
        "¿Se ha sentido desanimado(a) y triste?",
        "¿Se ha sentido agotado(a)?",
        "¿Se ha sentido feliz?",
        "¿Se ha sentido cansado(a)?",
        "Reducir actividades sociales por problemas físicos o emocionales",
        "Realizar menos de lo deseado por problemas físicos o emocionales",
        "No ha realizado el trabajo cuidadosamente por problemas emocionales",
        "Interferencia de problemas emocionales en actividades sociales",
        "¿Ha sentido nerviosismo o tensión?",
        "¿Se ha sentido tan bajo(a) de ánimo que nada le animaba?",
    ]
    return build_instrument_pdf(
        "sf-36-calidad-vida-salud-espanol.pdf",
        "SF-36 en Español",
        "Short Form Health Survey — Calidad de vida relacionada con la salud",
        "Autoreporte sobre las <b>últimas 4 semanas</b>. 36 ítems, 8 dominios. "
        "Transformar a escala 0–100 según manual oficial.",
        items,
        "<b>DOMINIOS (0–100):</b> PF _____ · RP _____ · BP _____ · GH _____ · VT _____ · SF _____ · RE _____ · MH _____",
        ["Dominio", "Interpretación", "Acción sugerida"],
        [
            ["≥ 50", "Por encima del promedio", "Monitoreo rutinario"],
            ["25 – 49", "Por debajo del promedio", "Explorar factores médicos/psicosociales"],
            ["< 25", "Muy deteriorado", "Intervención integral"],
        ],
        "Evalúa calidad de vida con SF-36 en Kalyo — kalyo.io",
        "Ware JE Jr, Sherbourne CD. The MOS 36-item short-form health survey. Med Care. 1992;30(6):473-483.",
        scale_note="Consulte claves de puntuación por ítem en manual SF-36 (2–6 opciones según ítem).",
        scale_headers=LIKERT_1_5,
    )


def gen_whodas():
    items = [
        "Concentrarse en hacer algo durante diez minutos",
        "Recordar hacer cosas importantes",
        "Analizar y encontrar soluciones a problemas cotidianos",
        "Aprender una tarea nueva (p. ej. aprender una ruta)",
        "Generalmente, comprender lo que dice la gente",
        "Iniciar y mantener una conversación",
        "Ponerse de pie durante periodos prolongados (30 min)",
        "Levantarse de estar sentado(a)",
        "Moverse dentro de su casa",
        "Salir de su casa",
        "Caminar largas distancias (1 km o más)",
        "Lavarse todo el cuerpo",
        "Vestirse",
        "Comer",
        "Permanecer solo(a) durante uno o más días",
        "Relacionarse con personas cercanas",
        "Mantener amistades",
        "Relacionarse con personas que no conoce",
        "Hacer nuevas amistades",
        "Relaciones sexuales",
        "Cuidar responsabilidades del hogar",
        "Realizar tareas domésticas más importantes",
        "Terminar todas las tareas domésticas necesarias",
        "Terminar el trabajo escolar o laboral a tiempo",
        "Realizar las tareas diarias del trabajo o escuela",
        "Problemas para participar en actividades comunitarias",
        "Barreras o dificultades en la vida diaria",
        "Problemas para realizar acciones cotidianas por emociones",
        "Dificultad para desempeñar su trabajo (incluido trabajo en casa)",
        "Dificultad para realizar tareas o responsabilidades",
        "Incapacidad para realizar actividades cotidianas",
        "Dificultad para mantener amistades",
        "Problemas emocionales que afectan relaciones",
        "Dificultad para desempeñarse en actividades comunitarias",
        "Tiempo dedicado a su salud o condición",
        "Impacto emocional de su condición de salud",
    ]
    return build_instrument_pdf(
        "whodas-discapacidad-funcionamiento-espanol.pdf",
        "WHODAS 2.0 en Español",
        "WHO Disability Assessment Schedule 2.0",
        "Indique la dificultad durante los <b>últimos 30 días</b>. 36 ítems, 6 dominios. "
        "Escala 1–5. Tiempo: 20 min.",
        items,
        "<b>PUNTAJE GLOBAL:</b> _____ / 100",
        ["Puntaje", "Nivel", "Acción sugerida"],
        [
            ["0 – 4", "Sin discapacidad", "Monitoreo rutinario"],
            ["5 – 24", "Leve", "Rehabilitación; apoyo psicosocial"],
            ["25 – 49", "Moderada", "Intervención multidisciplinaria"],
            ["50 – 100", "Severa", "Plan integral de rehabilitación"],
        ],
        "Registra discapacidad funcional con WHODAS 2.0 en Kalyo — kalyo.io",
        "WHO. Measuring Health and Disability: Manual for WHODAS 2.0. 2010.",
        scale_note="1 = Ninguna · 2 = Leve · 3 = Moderada · 4 = Severa · 5 = Extrema / no puede",
        scale_headers=LIKERT_1_5,
    )


def gen_neo_ffi():
    items = [
        "Me gusta tener muchas personas a mi alrededor",
        "No me interesan mucho los demás (inv.)",
        "Me siento cómodo(a) entre la gente",
        "Prefiero estar solo(a) que con mucha gente (inv.)",
        "Soy una persona muy activa y enérgica",
        "Prefiero leer que ir a fiestas (inv.)",
        "Hablo con muchas personas diferentes en fiestas",
        "Evito llamar la atención sobre mí (inv.)",
        "No me importa ser el centro de atención",
        "No hablo mucho (inv.)",
        "Me gusta ayudar a los demás",
        "No me interesa el bienestar de los demás (inv.)",
        "Soy considerado(a) y amable con casi todos",
        "Insulto a la gente (inv.)",
        "Siento las emociones de los demás",
        "No me interesan los problemas ajenos (inv.)",
        "Tengo un corazón blando",
        "No estoy interesado(a) en los demás (inv.)",
        "Dedico tiempo a los demás",
        "Me siento indiferente ante sentimientos ajenos (inv.)",
        "Siempre estoy preparado(a)",
        "Dejo mis pertenencias por ahí (inv.)",
        "Presto atención a los detalles",
        "Hago un desorden de las cosas (inv.)",
        "Sigo un horario estricto",
        "A menudo olvido devolver las cosas (inv.)",
        "Me gusta el orden",
        "Evito mis responsabilidades (inv.)",
        "Soy exacto(a) en mi trabajo",
        "A menudo olvido poner las cosas en su lugar (inv.)",
        "Me preocupo fácilmente",
        "Estoy relajado(a) la mayor parte del tiempo (inv.)",
        "Me altero fácilmente",
        "Rara vez me siento triste (inv.)",
        "Me estreso fácilmente",
        "Suelo estar tranquilo(a) (inv.)",
        "Me pongo nervioso(a) con facilidad",
        "Rara vez me siento deprimido(a) (inv.)",
        "Me preocupo por muchas cosas",
        "Soy emocionalmente estable (inv.)",
        "Tengo una imaginación activa",
        "No me interesan las ideas abstractas (inv.)",
        "Tengo excelentes ideas",
        "No tengo buena imaginación (inv.)",
        "Entiendo las cosas rápidamente",
        "No me gusta pensar en ideas complejas (inv.)",
        "Uso palabras difíciles",
        "Dedico poco tiempo a reflexionar (inv.)",
        "Tengo ideas originales",
        "Me cuesta entender ideas abstractas (inv.)",
        "Estoy lleno(a) de ideas",
        "No me interesan las ideas teóricas (inv.)",
        "Valoro el arte y la estética",
        "Pocas veces noto reacciones emocionales en el arte (inv.)",
        "Disfruto escuchar música clásica",
        "No me interesan las obras de arte (inv.)",
        "Disfruto leer poesía",
        "No disfruto ir a museos (inv.)",
        "Disfruto de películas poco convencionales",
        "Prefiero trabajos rutinarios (inv.)",
    ]
    return build_instrument_pdf(
        "neo-pi-r-personalidad-espanol.pdf",
        "NEO-FFI en Español",
        "NEO Five-Factor Inventory — Versión breve NEO PI-R",
        "Indique su grado de acuerdo. <b>60 ítems</b>, 5 factores (N, E, O, A, C). Escala 1–5. Tiempo: 10–15 min.",
        items,
        "<b>PUNTAJES:</b> N _____ · E _____ · O _____ · A _____ · C _____",
        ["T score", "Nivel", "Acción sugerida"],
        [
            ["45 – 55", "Promedio", "Rango normativo"],
            ["56 – 65", "Elevado", "Explorar implicaciones clínicas"],
            ["≥ 66", "Muy elevado", "Integrar con evaluación de personalidad"],
        ],
        "Evalúa personalidad con NEO-FFI en Kalyo — kalyo.io",
        "Costa PT, McCrae RR. NEO-FFI Professional Manual. PAR. 1992.",
        scale_note="1 = Totalmente en desacuerdo · 5 = Totalmente de acuerdo (recodificar ítems inv.)",
        scale_headers=LIKERT_1_5,
    )


def gen_pid5_bf():
    items = [
        "Las emociones me confunden",
        "Mis emociones son intensas pero cambian rápidamente",
        "Tengo emociones que no entiendo",
        "Pido a otros que me ayuden a entender mis emociones",
        "Soy una persona emocional",
        "Me siento fuera de lugar en situaciones sociales",
        "Evito situaciones sociales por miedo a ser criticado(a)",
        "Me siento incómodo(a) cuando conozco gente nueva",
        "Evito trabajos que impliquen contacto con personas",
        "A menudo siento que no encajo con los demás",
        "A menudo me siento como un observador externo de mí mismo(a)",
        "Me siento distante de las personas que me importan",
        "Rara vez siento una conexión emocional con otras personas",
        "Me siento vacío(a) por dentro",
        "Me siento desconectado(a) de la realidad",
        "Manipulo a otros para conseguir lo que quiero",
        "No me importa si tengo que engañar a alguien para conseguir lo que quiero",
        "He engañado o estafado a otros",
        "He engañado a alguien para conseguir dinero",
        "He engañado a alguien para conseguir algo que quería",
        "Actúo sin pensar en las consecuencias",
        "Hago cosas impulsivas que luego lamento",
        "Tengo dificultad para mantener un trabajo o cumplir obligaciones",
        "A menudo actúo sin considerar las consecuencias",
        "Tengo dificultad para planificar con anticipación",
        "A menudo tengo experiencias inusuales",
        "A menudo tengo pensamientos o creencias que otros consideran extraños",
        "A menudo tengo experiencias que otros consideran extrañas",
        "A menudo tengo pensamientos o creencias inusuales",
        "A menudo tengo experiencias que otros no entienden",
    ][:25]
    return build_instrument_pdf(
        "pid-5-bf-personalidad-dsm5-espanol.pdf",
        "PID-5-BF en Español",
        "Personality Inventory for DSM-5 — Brief Form (25 ítems)",
        "Indique cuánto se identifica con cada afirmación. <b>25 ítems</b>, 5 dominios del modelo "
        "alternativo DSM-5. Escala 0–3. Tiempo: 5–10 min.",
        items,
        "<b>DOMINIOS:</b> Afecto negativo _____ · Antagonismo _____ · Desinhibición _____ · Psicoticismo _____ · Evitación _____",
        ["Percentil", "Nivel", "Acción sugerida"],
        [
            ["≤ 84", "Normal", "Monitoreo rutinario"],
            ["85 – 94", "Elevado", "Explorar en entrevista clínica"],
            ["95 – 97", "Muy elevado", "Evaluación de personalidad patológica"],
            ["≥ 98", "Extremo", "Evaluación especializada"],
        ],
        "Evalúa rasgos de personalidad con PID-5-BF en Kalyo — kalyo.io",
        "Krueger RF et al. Initial construction and validation of the PID-5-BF. Psychol Assess. 2012;24(4):885-897.",
        scale_note="0 = Muy falso · 1 = Moderadamente falso · 2 = Moderadamente cierto · 3 = Muy cierto",
        scale_headers=LIKERT_0_3,
    )


def gen_epq_r():
    items = [
        "¿Tiene muchos amigos diferentes?",
        "¿Le gusta ir a fiestas y reuniones?",
        "¿Le gusta tener mucha gente a su alrededor?",
        "¿Prefiere leer un libro que ir a una fiesta?",
        "¿Le gusta hablar con la gente?",
        "¿Le gusta hacer cosas en las que hay mucha gente?",
        "¿Le gusta ir a bailar?",
        "¿Le gusta hablar con desconocidos?",
        "¿Le gusta ir a fiestas?",
        "¿Le gusta tener muchas actividades sociales?",
        "¿Se siente triste con frecuencia?",
        "¿Se siente tenso(a) o alterado(a)?",
        "¿Se preocupa por cosas sin importancia?",
        "¿Se siente infeliz?",
        "¿Tiene cambios de humor frecuentes?",
        "¿Se siente solo(a)?",
        "¿Se siente tenso(a) o nervioso(a)?",
        "¿Se siente deprimido(a) o melancólico(a)?",
        "¿Se siente ansioso(a) sin razón?",
        "¿Se siente infeliz sin razón?",
        "¿Se siente tenso(a) o alterado(a)?",
        "¿Se siente infeliz?",
        "¿Se siente tenso(a)?",
        "¿Se siente deprimido(a)?",
        "¿Le gusta la aventura?",
        "¿Le gusta hacer cosas emocionantes?",
        "¿Le gusta tomar riesgos?",
        "¿Le gusta la emoción?",
        "¿Le gusta hacer cosas peligrosas?",
        "¿Le gusta la aventura y el riesgo?",
        "¿Le gusta hacer cosas emocionantes?",
        "¿Le gusta tomar riesgos?",
        "¿Le gusta la emoción?",
        "¿Le gusta hacer cosas peligrosas?",
        "¿Le gusta la aventura?",
        "¿Le gusta hacer cosas emocionantes?",
        "¿Le gusta tomar riesgos?",
        "¿Le gusta la emoción?",
        "¿Le gusta hacer cosas peligrosas?",
        "¿Le gusta la aventura?",
        "¿Dice mentiras con frecuencia?",
        "¿Ha dicho alguna vez algo malo de alguien?",
        "¿Ha engañado alguna vez a alguien?",
        "¿Ha robado algo?",
        "¿Ha engañado a alguien?",
        "¿Ha robado algo de poco valor?",
        "¿Ha robado algo de valor?",
        "¿Ha engañado a alguien para conseguir dinero?",
    ]
    return build_instrument_pdf(
        "epq-r-cuestionario-eysenck-espanol.pdf",
        "EPQ-R en Español",
        "Eysenck Personality Questionnaire — Revised (versión abreviada 48 ítems)",
        "Responda Sí o No según cómo es generalmente. <b>48 ítems</b>: Extraversión, Neuroticismo, "
        "Psicoticismo y escala de Mentira. Tiempo: 10–15 min.",
        items,
        "<b>PUNTAJES:</b> E _____ · N _____ · P _____ · L _____",
        ["Dimensión", "Interpretación", "Acción sugerida"],
        [
            ["E alta", "Extraversión", "Explorar estilo interpersonal"],
            ["N alta", "Neuroticismo elevado", "Evaluar ansiedad/depresión comórbida"],
            ["P alta", "Psicoticismo elevado", "Evaluación de personalidad/impulsividad"],
            ["L alta", "Posible sesgo de deseabilidad", "Interpretar con cautela"],
        ],
        "Evalúa personalidad con EPQ-R en Kalyo — kalyo.io",
        "Eysenck HJ, Eysenck SBG. Manual for the Eysenck Personality Questionnaire. Hodder & Stoughton. 1975.",
        scale_note="Responda Sí o No a cada afirmación según manual EPQ-R.",
        scale_headers=YES_NO,
    )
