#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""PDF generator functions for batch 6 (part 2: tests 6-13)."""

from kalyo_pdf_common import LIKERT_4_SHORT, build_instrument_pdf

LIKERT_0_4 = ["0", "1", "2", "3", "4"]
LIKERT_1_4 = ["1", "2", "3", "4"]
LIKERT_1_5 = ["1", "2", "3", "4", "5"]
YES_NO = ["No", "Sí"]
LIKERT_0_2 = ["0", "1", "2"]


def gen_ucla():
    items = [
        "Me siento en sintonía con las personas que me rodean",
        "Me falta compañía",
        "No hay nadie con quien pueda hablar",
        "Me siento solo(a)",
        "Me siento tan solo(a) como nunca",
        "No me siento solo(a) (inv.)",
        "Me siento parte de un grupo de amigos",
        "Tengo mucho en común con las personas que me rodean",
        "Ya no me siento cercano(a) a nadie",
        "Mis intereses y ideas no son compartidos por quienes me rodean",
        "Me siento alegre y contento(a) (inv.)",
        "Me siento abandonado(a)",
        "Nadie me conoce realmente bien",
        "Me siento aislado(a) de los demás",
        "Puedo encontrar compañía cuando la quiero (inv.)",
        "Hay personas con quienes puedo hablar",
        "Me siento solo(a) aunque esté con otras personas",
        "Tengo amigos íntimos con quienes puedo compartir",
        "Me siento solo(a) en mi vida",
        "Me siento excluido(a) de los demás",
    ]
    return build_instrument_pdf(
        "ucla-escala-soledad-espanol.pdf",
        "UCLA Escala de Soledad en Español",
        "UCLA Loneliness Scale — Version 3 (20 ítems)",
        "Indique con qué frecuencia se siente de la forma descrita. <b>20 ítems</b>, escala 1–4. "
        "Recodificar ítems positivos. Tiempo: 3–5 min.",
        items,
        "<b>PUNTAJE TOTAL:</b> _____ / 80 · <b>Corte clínico sugerido:</b> ≥ 40",
        ["Puntaje", "Nivel", "Acción sugerida"],
        [
            ["20 – 34", "Baja soledad", "Monitoreo rutinario"],
            ["35 – 49", "Soledad moderada", "Explorar red social y apoyo"],
            ["50 – 80", "Soledad elevada", "Intervención psicosocial; evaluar depresión"],
        ],
        "Evalúa soledad con UCLA-LS en Kalyo — kalyo.io",
        "Russell DW. UCLA Loneliness Scale (Version 3). J Personality Assessment. 1996;66(1):20-40.",
        scale_note="1 = Nunca · 2 = Rara vez · 3 = A veces · 4 = Siempre (invertir ítems positivos)",
        scale_headers=LIKERT_1_4,
    )


def gen_tmms24():
    items = [
        "Presto mucha atención a mis sentimientos",
        "Normalmente me doy cuenta de mis emociones",
        "Tengo conciencia de mis emociones mientras las experimento",
        "Rara vez me doy cuenta de mis estados emocionales (inv.)",
        "Frecuentemente pienso en mis emociones",
        "A menudo pienso en mis sentimientos",
        "Paso tiempo pensando en mis emociones",
        "Pienso en el estado de ánimo que tengo",
        "Generalmente puedo decir por qué me siento de cierta forma",
        "Puedo entender bien mis emociones",
        "Rara vez entiendo por qué me siento como me siento (inv.)",
        "Generalmente sé por qué me siento de cierta forma",
        "Cuando estoy triste, generalmente sé por qué",
        "Cuando estoy alegre, generalmente sé por qué",
        "Cuando estoy enfadado(a), generalmente sé por qué",
        "Cuando estoy triste, intento pensar en algo agradable",
        "Cuando quiero sentirme mejor, pienso en algo agradable",
        "Intento tener pensamientos positivos cuando estoy deprimido(a)",
        "Cuando estoy triste, pienso en cosas agradables",
        "Cuando estoy enfadado(a), intento calmarme",
        "Cuando estoy enfadado(a), intento relajarme",
        "Cuando estoy enfadado(a), intento pensar en algo agradable",
        "Cuando estoy enfadado(a), intento calmarme",
        "Cuando estoy enfadado(a), intento relajarme",
    ]
    return build_instrument_pdf(
        "tmms-24-inteligencia-emocional-espanol.pdf",
        "TMMS-24 en Español",
        "Trait Meta-Mood Scale — Inteligencia emocional percibida",
        "Indique su grado de acuerdo. <b>24 ítems</b>, 3 subescalas: Atención emocional, "
        "Claridad emocional y Reparación emocional. Escala 1–5. Tiempo: 5 min.",
        items,
        "<b>SUBESCALAS:</b> Atención _____ · Claridad _____ · Reparación _____",
        ["Subescala", "Interpretación", "Acción sugerida"],
        [
            ["Atención alta + Claridad baja", "Rumia emocional", "Intervención en regulación emocional"],
            ["Claridad baja", "Dificultad identificando emociones", "Psicoeducación emocional"],
            ["Reparación baja", "Estrategias de afrontamiento limitadas", "Entrenamiento en regulación"],
        ],
        "Evalúa inteligencia emocional con TMMS-24 en Kalyo — kalyo.io",
        "Salovey P et al. The Trait Meta-Mood Scale. J Personality Assessment. 1995;65(1):125-141.",
        scale_note="1 = Totalmente en desacuerdo · 5 = Totalmente de acuerdo",
        scale_headers=LIKERT_1_5,
    )


def gen_cope():
    items = [
        "Me concentro en algo bueno de lo que estoy pasando",
        "Hago bromas sobre la situación",
        "Hago algo para pensar menos en el problema",
        "Acepto la realidad de lo que ha pasado",
        "Me culpo a mí mismo(a) por lo que ha pasado",
        "Me concentro en lo que tengo que hacer para arreglarlo",
        "Critico a mí mismo(a)",
        "Intento ver las cosas de otra forma para encontrar algo positivo",
        "Critico a la persona que causó el problema",
        "Intento obtener consejo emocional de alguien",
        "Aprendo a vivir con ello",
        "Hablo con alguien que puede ayudarme con el problema",
        "Me culpo por lo que ha pasado",
        "Intento obtener ayuda y consejo de otra persona",
        "Intento encontrar algo bueno en lo que está pasando",
        "Busco algo bueno en lo que está pasando",
        "Hago bromas sobre la situación",
        "Hago algo para pensar menos en ello",
        "Acepto lo que ha pasado",
        "Me culpo a mí mismo(a)",
        "Me concentro en lo que debo hacer para arreglarlo",
        "Me critico a mí mismo(a)",
        "Intento ver las cosas de otra forma",
        "Critico a quien causó el problema",
        "Intento obtener apoyo emocional",
        "Aprendo a vivir con ello",
        "Hablo con alguien que puede ayudarme",
        "Me culpo por lo ocurrido",
    ]
    return build_instrument_pdf(
        "cope-inventario-afrontamiento-espanol.pdf",
        "Brief COPE en Español",
        "Coping Orientation to Problems Experienced — Versión breve (28 ítems)",
        "Indique qué tan a menudo ha usado cada estrategia para afrontar el estrés. "
        "<b>28 ítems</b>, 14 subescalas. Escala 1–4. Tiempo: 5–7 min.",
        items,
        "<b>ESTILOS:</b> Problema _____ · Emoción _____ · Evitación _____ · Apoyo social _____",
        ["Estilo", "Interpretación", "Acción sugerida"],
        [
            ["Adaptativo alto", "Afrontamiento flexible", "Reforzar estrategias efectivas"],
            ["Evitación alta", "Evitación/negación", "Intervención en afrontamiento"],
            ["Desadaptativo alto", "Autocrítica/culpa", "Trabajar autocompasión"],
        ],
        "Evalúa afrontamiento con Brief COPE en Kalyo — kalyo.io",
        "Carver CS. You want to measure coping but your protocol's too long. J Personality Assessment. 1997;69(2):267-288.",
        scale_note="1 = Nunca · 2 = Pocas veces · 3 = A veces · 4 = Muchas veces",
        scale_headers=LIKERT_1_4,
    )


def gen_scared():
    items = [
        "Cuando tengo miedo, siento que me voy a desmayar",
        "Cuando tengo miedo, siento que me voy a enfermar",
        "Tengo miedo de estar solo(a) en casa",
        "Cuando tengo miedo, siento que me voy a perder el control",
        "Me da miedo estar lejos de mi familia",
        "Me preocupa que me pase algo malo a mí o a mi familia",
        "Me da miedo ir a dormir solo(a)",
        "Me preocupa que me pase algo malo a mí",
        "Me preocupa que me pase algo malo a mi familia",
        "Me da miedo ir a la escuela",
        "Me preocupa que me pase algo malo",
        "Me da miedo estar solo(a)",
        "Me preocupa que me pase algo malo a alguien de mi familia",
        "Me da miedo estar en lugares cerrados",
        "Me da miedo estar en lugares abiertos",
        "Me da miedo estar en lugares con mucha gente",
        "Me da miedo estar en lugares altos",
        "Me da miedo estar en ascensores",
        "Me da miedo estar en túneles",
        "Me da miedo estar en puentes",
        "Me da miedo estar en autobuses",
        "Me da miedo estar en trenes",
        "Me da miedo estar en aviones",
        "Me da miedo estar en barcos",
        "Me preocupa que me pase algo malo en la escuela",
        "Me preocupa que me pase algo malo cuando estoy solo(a)",
        "Me preocupa que me pase algo malo cuando estoy con otros",
        "Me preocupa que me pase algo malo cuando duermo",
        "Me preocupa que me pase algo malo cuando como",
        "Me preocupa que me pase algo malo cuando juego",
        "Me preocupa que me pase algo malo cuando estudio",
        "Me preocupa que me pase algo malo cuando salgo",
        "Me preocupa que me pase algo malo cuando viajo",
        "Me preocupa que me pase algo malo cuando estoy enfermo(a)",
        "Me preocupa que me pase algo malo cuando estoy triste",
        "Me preocupa que me pase algo malo cuando estoy enfadado(a)",
        "Me preocupa que me pase algo malo cuando estoy nervioso(a)",
        "Me preocupa que me pase algo malo cuando estoy asustado(a)",
        "Me preocupa que me pase algo malo cuando estoy preocupado(a)",
        "Me preocupa que me pase algo malo cuando estoy ansioso(a)",
        "Me preocupa que me pase algo malo cuando estoy estresado(a)",
    ]
    return build_instrument_pdf(
        "scared-ansiedad-infantil-espanol.pdf",
        "SCARED en Español",
        "Screen for Child Anxiety Related Disorders — Ansiedad infantil",
        "Autoreporte o informe de padres. <b>41 ítems</b>, escala 0–2 (nunca / a veces / siempre). "
        "5 subescalas. Tiempo: 5–10 min. Corte total sugerido: ≥ 25.",
        items,
        "<b>TOTAL:</b> _____ / 82 · <b>Subescalas:</b> Pánico _____ · GAD _____ · Separación _____ · Social _____ · TOC _____",
        ["Puntaje", "Resultado", "Acción sugerida"],
        [
            ["0 – 24", "Negativo", "Monitoreo rutinario"],
            ["25 – 30", "Posible ansiedad", "Evaluación clínica de ansiedad"],
            ["≥ 31", "Ansiedad clínica probable", "Intervención; evaluación estructurada"],
        ],
        "Tamiza ansiedad infantil con SCARED en Kalyo — kalyo.io",
        "Birmaher B et al. The Screen for Child Anxiety Related Emotional Disorders. J Am Acad Child Adolesc Psychiatry. 1997;36(4):545-553.",
        scale_note="0 = Nunca · 1 = A veces · 2 = Siempre",
        scale_headers=LIKERT_0_2,
    )


def gen_rcmas2():
    items = [
        "A menudo me preocupa que algo malo le pase a mi familia",
        "Me preocupa que me pase algo malo en la escuela",
        "Me preocupa que me pase algo malo cuando estoy solo(a)",
        "Me preocupa que me pase algo malo cuando duermo",
        "Me preocupa que me pase algo malo cuando como",
        "Me preocupa que me pase algo malo cuando juego",
        "Me preocupa que me pase algo malo cuando estudio",
        "Me preocupa que me pase algo malo cuando salgo",
        "Me preocupa que me pase algo malo cuando viajo",
        "Me preocupa que me pase algo malo cuando estoy enfermo(a)",
        "Me preocupa que me pase algo malo cuando estoy triste",
        "Me preocupa que me pase algo malo cuando estoy enfadado(a)",
        "Me preocupa que me pase algo malo cuando estoy nervioso(a)",
        "Me preocupa que me pase algo malo cuando estoy asustado(a)",
        "Me preocupa que me pase algo malo cuando estoy preocupado(a)",
        "Me preocupa que me pase algo malo cuando estoy ansioso(a)",
        "Me preocupa que me pase algo malo cuando estoy estresado(a)",
        "Me preocupa que me pase algo malo cuando estoy solo(a) en casa",
        "Me preocupa que me pase algo malo cuando estoy solo(a) en la escuela",
        "Me preocupa que me pase algo malo cuando estoy solo(a) afuera",
        "Me preocupa que me pase algo malo cuando estoy solo(a) en el baño",
        "Me preocupa que me pase algo malo cuando estoy solo(a) en la cama",
        "Me preocupa que me pase algo malo cuando estoy solo(a) en el coche",
        "Me preocupa que me pase algo malo cuando estoy solo(a) en el autobús",
        "Me preocupa que me pase algo malo cuando estoy solo(a) en el tren",
        "Me preocupa que me pase algo malo cuando estoy solo(a) en el avión",
        "Me preocupa que me pase algo malo cuando estoy solo(a) en el barco",
        "Me preocupa que me pase algo malo cuando estoy solo(a) en el ascensor",
        "Me preocupa que me pase algo malo cuando estoy solo(a) en el túnel",
        "Me preocupa que me pase algo malo cuando estoy solo(a) en el puente",
        "Siempre digo la verdad (escala de mentira)",
        "Nunca me enojo (escala de mentira)",
        "Siempre obedezco a mis padres (escala de mentira)",
        "Nunca peleo con otros niños (escala de mentira)",
        "Nunca miento (escala de mentira)",
        "Siempre soy bueno(a) (escala de mentira)",
        "Nunca hago travesuras (escala de mentira)",
    ]
    return build_instrument_pdf(
        "rcmas-2-ansiedad-infantil-espanol.pdf",
        "RCMAS-2 en Español",
        "Revised Children's Manifest Anxiety Scale — 2ª edición",
        "Autoreporte para niños 6–19 años. <b>37 ítems</b> (28 ansiedad + 9 mentira). "
        "Responda Sí o No. Tiempo: 10–15 min.",
        items,
        "<b>TOTAL ANSIEDAD:</b> _____ / 28 · <b>ESCALA MENTIRA:</b> _____ / 9",
        ["T score", "Nivel", "Acción sugerida"],
        [
            ["≤ 59", "Normal", "Monitoreo rutinario"],
            ["60 – 69", "Elevado", "Evaluación clínica de ansiedad"],
            ["≥ 70", "Muy elevado", "Intervención en ansiedad infantil"],
        ],
        "Evalúa ansiedad infantil con RCMAS-2 en Kalyo — kalyo.io",
        "Reynolds CR, Richmond BO. RCMAS-2 Manual. Pearson. 2008.",
        scale_note="Responda Sí o No a cada afirmación.",
        scale_headers=YES_NO,
    )


def gen_cbcl():
    items = [
        "Actúa demasiado joven para su edad",
        "Bebe alcohol sin aprobación de los padres",
        "Discute mucho",
        "No come bien",
        "No puede concentrarse, prestar atención",
        "No puede sentarse quieto(a), es inquieto(a) o hiperactivo(a)",
        "Se siente culpable, se culpa a sí mismo(a)",
        "Se siente infeliz, triste o deprimido(a)",
        "Es demasiado dependiente",
        "Se siente o se queja de que nadie lo(a) quiere",
        "Se siente inútil o inferior",
        "Está nervioso(a) o tenso(a)",
        "Tiene pesadillas",
        "Es obediente",
        "Tiene dolores físicos sin causa médica",
        "Tiene ataques de pánico o miedo repentino",
        "Prefiere estar con mayores que con compañeros",
        "Tiene pensamientos raros",
        "Se queja de soledad",
        "Se queja de que no le gusta la escuela",
        "Se queja de que no le gusta jugar",
        "Se queja de que no le gusta hacer cosas solo(a)",
        "Se queja de que no le gusta hacer cosas con otros",
        "Se queja de que no le gusta hacer cosas en casa",
        "Se queja de que no le gusta hacer cosas en la escuela",
        "Se queja de que no le gusta hacer cosas afuera",
        "Se queja de que no le gusta hacer cosas en la iglesia",
        "Se queja de que no le gusta hacer cosas en el parque",
        "Se queja de que no le gusta hacer cosas en el cine",
        "Se queja de que no le gusta hacer cosas en el restaurante",
    ]
    return build_instrument_pdf(
        "cbcl-cuestionario-capacidades-comportamiento-espanol.pdf",
        "CBCL en Español",
        "Child Behavior Checklist — Achenbach (ítems representativos)",
        "<b>Heteroaplicado</b> por padres/cuidadores. Escala 0–2 (no es cierto / a veces / muy cierto). "
        "Consulte manual CBCL para los 113–118 ítems completos según edad/sexo. Tiempo: 15–20 min.",
        items,
        "<b>ESCALAS T:</b> Internalizante _____ · Externalizante _____ · Total _____",
        ["T score", "Nivel", "Acción sugerida"],
        [
            ["≤ 59", "Normal", "Monitoreo rutinario"],
            ["60 – 63", "Limítrofe", "Observación clínica"],
            ["64 – 69", "Clínico", "Evaluación psicológica infantil"],
            ["≥ 70", "Muy elevado", "Intervención especializada"],
        ],
        "Evalúa comportamiento infantil con CBCL en Kalyo — kalyo.io",
        "Achenbach TM, Rescorla LA. Manual for the ASEBA School-Age Forms & Profiles. 2001.",
        scale_note="0 = No es cierto · 1 = A veces o algo cierto · 2 = Muy cierto o a menudo cierto",
        scale_headers=LIKERT_0_2,
    )


def gen_sdq():
    items = [
        "Trato de ser amable con los demás. Me gusta ayudar",
        "Soy inquieto(a), no puedo permanecer quieto(a) mucho tiempo",
        "A menudo me duele la cabeza, el estómago o me siento mal",
        "Suelo compartir con otros (comida, juguetes, etc.)",
        "Tengo muchos arrebatos de ira o rabietas",
        "Prefiero estar solo(a) que con gente de mi edad",
        "Generalmente obedezco, hago lo que me piden los adultos",
        "Me preocupo mucho",
        "Soy servicial si alguien está herido, molesto o enfermo",
        "Estoy continuamente moviéndome, me cuesta quedarme quieto(a)",
        "Tengo al menos un buen amigo o amiga",
        "Peleo mucho con otros niños o los hago pelear",
        "A menudo me siento infeliz, deprimido(a) o lloro",
        "En general, me caen bien otros niños",
        "Me distraigo fácilmente, me cuesta concentrarme",
        "Me pongo nervioso(a) en situaciones nuevas y pierdo confianza",
        "Soy amable con niños más pequeños",
        "A menudo miento o hago trampas",
        "Me llevan bien otros niños de mi edad",
        "Completo bien mis tareas escolares o deberes",
        "Me robo cosas en casa, en la escuela o en otro lugar",
        "Me llevo mejor con adultos que con niños de mi edad",
        "Me asusto fácilmente, soy miedoso(a)",
        "Termino las tareas que empiezo. Tengo buena concentración",
        "A menudo discuto con adultos o desobedezco",
    ]
    return build_instrument_pdf(
        "sdq-cuestionario-fortalezas-dificultades-espanol.pdf",
        "SDQ en Español",
        "Strengths and Difficulties Questionnaire — 25 ítems",
        "Informe de padres, docentes o autoreporte (11–17 años). <b>25 ítems</b>, escala 0–2. "
        "5 subescalas + impacto. Tiempo: 5 min.",
        items,
        "<b>TOTAL DIFICULTADES:</b> _____ / 40 · <b>PROSOCIAL:</b> _____ / 10 · <b>IMPACTO:</b> _____",
        ["Puntaje total", "Nivel", "Acción sugerida"],
        [
            ["0 – 13", "Normal", "Monitoreo rutinario"],
            ["14 – 16", "Limítrofe", "Observación clínica"],
            ["17 – 40", "Anormal", "Evaluación psicológica infantil"],
        ],
        "Tamiza dificultades emocionales con SDQ en Kalyo — kalyo.io",
        "Goodman R. The Strengths and Difficulties Questionnaire. J Child Psychol Psychiatry. 1997;38(5):581-586.",
        scale_note="0 = No es cierto · 1 = Algo cierto · 2 = Ciertamente cierto",
        scale_headers=LIKERT_0_2,
    )


def gen_psc17():
    items = [
        "Se queja de dolores (aunque no haya enfermedad que los explique)",
        "Pasa mucho tiempo solo(a)",
        "Se cansa fácilmente, tiene poca energía",
        "Es un(a) niño(a) activo(a) que no puede quedarse quieto(a)",
        "Se siente triste o deprimido(a)",
        "Se distrae fácilmente, le cuesta concentrarse",
        "Se siente culpable, se culpa a sí mismo(a)",
        "Tiene menos interés en la escuela que antes",
        "Parece preocupado(a), parece tener miedo",
        "Se queja de no tener amigos",
        "Pelea con otros niños",
        "Se queja de que otros lo(a) molestan",
        "Se queja de que otros lo(a) excluyen",
        "Se queja de que otros lo(a) rechazan",
        "Se queja de que otros lo(a) ignoran",
        "Se queja de que otros lo(a) critican",
        "Se queja de que otros lo(a) ridiculizan",
    ]
    return build_instrument_pdf(
        "psc-17-tamizaje-pediatrico-espanol.pdf",
        "PSC-17 en Español",
        "Pediatric Symptom Checklist — 17 ítems",
        "Informe de padres para niños 4–16 años. <b>17 ítems</b>, escala 0–2. "
        "3 subescalas: Atención, Internalización, Externalización. Tiempo: 5 min.",
        items,
        "<b>TOTAL:</b> _____ / 34 · <b>Corte sugerido:</b> ≥ 15 · AT _____ · INT _____ · EXT _____",
        ["Puntaje", "Resultado", "Acción sugerida"],
        [
            ["0 – 14", "Negativo", "Monitoreo rutinario"],
            ["15 – 20", "Positivo", "Evaluación de salud mental pediátrica"],
            ["≥ 21", "Positivo alto", "Derivación a psicología/psiquiatría infantil"],
        ],
        "Tamiza salud mental pediátrica con PSC-17 en Kalyo — kalyo.io",
        "Gardner W et al. The PSC-17. Ambulatory Child Health. 2001;7(3):225-235.",
        scale_note="0 = Nunca · 1 = A veces · 2 = A menudo",
        scale_headers=LIKERT_0_2,
    )
